# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SJBR\StaticInfoTables\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  SJBR\StaticInfoTables\EventListener\AfterPackageActivationEventListener:
    tags:
      - name: event.listener
        identifier: 'staticInfoTablesListener'
        event: TYPO3\CMS\Core\Package\Event\AfterPackageActivationEvent
    public: true

  SJBR\StaticInfoTables\EventListener\AfterExtensionStaticDatabaseContentHasBeenImportedEventListener:
    tags:
      - name: event.listener
        identifier: 'staticInfoTablesListener'
        event: TYPO3\CMS\Extensionmanager\Event\AfterExtensionStaticDatabaseContentHasBeenImportedEvent
    public: true

  SJBR\StaticInfoTables\Configuration\TypoScript\ConfigurationHelper:
    public: true

  SJBR\StaticInfoTables\Hook\Backend\Form\FormDataProvider\TcaLabelProcessor:
    public: true

  SJBR\StaticInfoTables\Hook\Backend\Form\FormDataProvider\TcaSelectItemsProcessor:
    public: true